# Generated by Django 3.2.3 on 2021-05-26 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品运营类'), (2, '内容类')], verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=200, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳')], verbose_name='工作地点')),
                ('job_responsibilities', models.TextField(max_length=200, verbose_name='职位职责')),
                ('job_requirements', models.TextField(max_length=200, verbose_name='职位要求')),
                ('create_time', models.TimeField(verbose_name='创建时间')),
                ('updata_time', models.TimeField(verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
